# Generated by Django 3.2.11 on 2022-04-25 15:36

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0002_initial"),
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.TextField(max_length=254, verbose_name="Subtitle")),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "title",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title_block",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Title Block",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "paragraph",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "strikethrough",
                                                    "h3",
                                                    "h4",
                                                    "h5",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                ],
                                                label="Paragraph",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "largeimage",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "large_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Large Image", required=True
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "doubleimage",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image_1",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image 1", required=False
                                            ),
                                        ),
                                        (
                                            "image_2",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image 2", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        verbose_name="Body",
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.customimage",
                        verbose_name="Background Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
